[pytest]
addopts = "-m regression"
testpaths = tests
markers   =
  smoke: marks quick install/import tests that should run before heavier regression suites
  premerge: marks tests to run on every PR (deselect with -m "not premerge")
  regression: marks tests to run in regular regression (deselect with -m "not regression")
  postmerge: marks tests to run postmerge (deselect with -m "not postmerge")
  nightly: marks tests to run nightly (deselect with -m "not nightly")
