[pytest]
addopts = "-m regression"
testpaths = tests
markers   =
  premerge: marks tests as tests to run on every PR (default for all tests, deselect with '-m "not premerge")
  regression: marks tests as tests to run on regular regression (deselect with '-m "not regression"')
  postmerge: marks tests as tests to run postmerge (deselect with '-m "not postmerge"')
  nightly: marks tests as tests to run nightly (deselect with '-m "not nightly"')