[flake8]
max-line-length = 120
ignore = F405 

[tox]
envlist = smoke,premerge
pytest_display_ops = -vv --color=yes
pytest_report_ops = --junitxml=junit-{envname}.xml
pytest_compute_ops = --timeout-method=thread -n {env:NPROC:8}
pytest_coverage_ops = --cov-report xml --cov=sima_qat
pytest_tempdir_ops = --basetemp={envtmpdir}
pytest_ops = {[tox]pytest_display_ops} {[tox]pytest_report_ops} {[tox]pytest_compute_ops} {[tox]pytest_coverage_ops} {[tox]pytest_tempdir_ops}

[testenv:smoke]
passenv = GIT_HASH
extras = tests
install_command = pip install {packages}
commands = pytest {[tox]pytest_display_ops} {[tox]pytest_report_ops} {[tox]pytest_tempdir_ops} -rs -m "smoke" {posargs}

[testenv:premerge]
passenv = GIT_HASH 
extras = tests
deps = pytest-xdist
       coverage==5.0b2
       pytest-cov
       pytest-timeout
       pytypes
install_command = pip install {packages}
commands = pytest {[tox]pytest_ops} -rs -m "regression" {posargs}

[testenv:postmerge]
passenv = {[testenv:premerge]passenv}
extras = {[testenv:premerge]extras}
deps = {[testenv:premerge]deps}
install_command = {[testenv:premerge]install_command}
commands = pytest {[tox]pytest_ops} -m {envname} {posargs}

[testenv:nightly]
passenv = {[testenv:premerge]passenv} 
extras = {[testenv:premerge]extras}
deps = {[testenv:premerge]deps}
install_command = {[testenv:premerge]install_command}
commands = pytest --timeout=28800 {[tox]pytest_ops} -m {envname} {posargs}

