"""SiMa.ai quantization-aware training for strict INT8 deployment."""

from sima_qat.depthart import (
    DepthARTP64PreparationReport,
    build_depthart_dynamic_p64_compile_profile,
    enable_depthart_dynamic_p64_fake_quant,
    freeze_depthart_dynamic_p64,
    prepare_depthart_dynamic_p64,
    write_depthart_dynamic_p64_compile_profile,
)
from sima_qat.dynamic_p64 import (
    DepthARTDynamicP64Step,
    DynamicP64FakeQuant,
    DynamicP64Result,
    P64ProductFixedPoint,
    P64ResidualAddFixedPoint,
    P64ToStaticFakeQuant,
    P64ToStaticFixedPoint,
    StaticAffineInt8FakeQuant,
    StaticAffineInt8Result,
    StaticInt8Result,
    StaticInt8ToP64FixedPoint,
    compiler_exact_block_p64_product,
    compiler_exact_dynamic_p64,
    compiler_exact_p64_to_static,
    compiler_exact_residual_p64_add,
    compiler_exact_static_int8_to_p64,
    decode_p64,
    encode_p64,
)
from sima_qat.qat_api import (
    sima_export_onnx,
    sima_finalize_qat_model,
    sima_freeze_qat,
    sima_prepare_qat_model,
    sima_project_qat_to_target_grids,
    sima_qat_activation_diagnostics,
    sima_thaw_qat_scales,
)
from sima_qat.range_refinement import refine_activation_ranges
from sima_qat.session import (
    ActivationRangeRefinementReport,
    ActivationRangeSelector,
    QATBundle,
    QATCalibrationReport,
    QATRecipe,
    QATReport,
    QATSession,
    load_recipe,
    prepare,
)

__all__ = [
    "ActivationRangeRefinementReport",
    "ActivationRangeSelector",
    "DepthARTDynamicP64Step",
    "DepthARTP64PreparationReport",
    "DynamicP64FakeQuant",
    "DynamicP64Result",
    "P64ProductFixedPoint",
    "P64ResidualAddFixedPoint",
    "P64ToStaticFakeQuant",
    "P64ToStaticFixedPoint",
    "QATBundle",
    "QATCalibrationReport",
    "QATRecipe",
    "QATReport",
    "QATSession",
    "StaticAffineInt8FakeQuant",
    "StaticAffineInt8Result",
    "StaticInt8Result",
    "StaticInt8ToP64FixedPoint",
    "build_depthart_dynamic_p64_compile_profile",
    "compiler_exact_block_p64_product",
    "compiler_exact_dynamic_p64",
    "compiler_exact_p64_to_static",
    "compiler_exact_residual_p64_add",
    "compiler_exact_static_int8_to_p64",
    "decode_p64",
    "enable_depthart_dynamic_p64_fake_quant",
    "encode_p64",
    "freeze_depthart_dynamic_p64",
    "load_recipe",
    "prepare",
    "prepare_depthart_dynamic_p64",
    "refine_activation_ranges",
    "sima_export_onnx",
    "sima_finalize_qat_model",
    "sima_freeze_qat",
    "sima_prepare_qat_model",
    "sima_project_qat_to_target_grids",
    "sima_qat_activation_diagnostics",
    "sima_thaw_qat_scales",
    "write_depthart_dynamic_p64_compile_profile",
]
